# Generated by Django 5.1 on 2024-09-16 14:03

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_post_delete_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='descripcion',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='imagen',
            field=models.ImageField(blank=True, default='imagen_def.jpg', null=True, upload_to=''),
        ),
    ]
